AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1             # Try to increase epoch size i.e. 200,300
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01

